import type { InvestmentType, MarketRates } from '@/types'

export const DEFAULT_MARKET_RATES: MarketRates = {
  cdi: 10.65,
  selic: 10.75,
  ipca: 4.5,
}

export const DEFAULT_INFLATION = 4.5

export const INVESTMENT_TYPES: InvestmentType[] = [
  {
    id: 'poupanca',
    name: 'Poupança',
    shortName: 'Poupança',
    category: 'savings',
    rateBasis: 'fixed',
    defaultRate: 6.17,
    taxExempt: true,
    fgcProtected: true,
    risk: 'low',
    liquidity: 'daily',
    minInvestment: 0,
    color: '#5BA8A0',
  },
  {
    id: 'cdb',
    name: 'CDB',
    shortName: 'CDB',
    category: 'fixed-income',
    rateBasis: 'cdi',
    defaultRate: 102,
    taxExempt: false,
    fgcProtected: true,
    risk: 'low',
    liquidity: 'maturity',
    minInvestment: 100,
    color: '#C9A24B',
  },
  {
    id: 'lci-lca',
    name: 'LCI / LCA',
    shortName: 'LCI/LCA',
    category: 'fixed-income',
    rateBasis: 'cdi',
    defaultRate: 92,
    taxExempt: true,
    fgcProtected: true,
    risk: 'low',
    liquidity: 'maturity',
    minInvestment: 1000,
    color: '#3FB984',
  },
  {
    id: 'tesouro-selic',
    name: 'Tesouro Selic',
    shortName: 'T. Selic',
    category: 'treasury',
    rateBasis: 'selic',
    defaultRate: 100,
    taxExempt: false,
    fgcProtected: false,
    risk: 'low',
    liquidity: 'daily',
    minInvestment: 50,
    color: '#6E84B8',
  },
  {
    id: 'tesouro-prefixado',
    name: 'Tesouro Prefixado',
    shortName: 'T. Pré',
    category: 'treasury',
    rateBasis: 'fixed',
    defaultRate: 11.5,
    taxExempt: false,
    fgcProtected: false,
    risk: 'medium',
    liquidity: 'maturity',
    minInvestment: 50,
    color: '#B5728C',
  },
  {
    id: 'tesouro-ipca',
    name: 'Tesouro IPCA+',
    shortName: 'T. IPCA+',
    category: 'treasury',
    rateBasis: 'ipca',
    defaultRate: 6.0,
    taxExempt: false,
    fgcProtected: false,
    risk: 'medium',
    liquidity: 'maturity',
    minInvestment: 50,
    color: '#C77B4A',
  },
  {
    id: 'acoes',
    name: 'Ações B3',
    shortName: 'Ações',
    category: 'variable-income',
    rateBasis: 'custom',
    defaultRate: 12,
    customRate: 12,
    flatTaxRate: 0.15,
    taxExempt: false,
    fgcProtected: false,
    risk: 'high',
    liquidity: 'daily',
    minInvestment: 0,
    color: '#D98A4B',
  },
  {
    id: 'fii',
    name: 'Fundos Imobiliários',
    shortName: 'FIIs',
    category: 'variable-income',
    rateBasis: 'custom',
    defaultRate: 10,
    customRate: 10,
    taxExempt: true,
    fgcProtected: false,
    risk: 'high',
    liquidity: 'daily',
    minInvestment: 0,
    color: '#C2607F',
  },
  {
    id: 'etf',
    name: 'ETF',
    shortName: 'ETF',
    category: 'variable-income',
    rateBasis: 'custom',
    defaultRate: 11,
    customRate: 11,
    flatTaxRate: 0.15,
    taxExempt: false,
    fgcProtected: false,
    risk: 'high',
    liquidity: 'daily',
    minInvestment: 0,
    color: '#9B6DB0',
  },
  {
    id: 'dolar',
    name: 'Dólar',
    shortName: 'Dólar',
    category: 'variable-income',
    rateBasis: 'custom',
    defaultRate: 6,
    customRate: 6,
    flatTaxRate: 0.15,
    taxExempt: false,
    fgcProtected: false,
    risk: 'medium',
    liquidity: 'daily',
    minInvestment: 0,
    color: '#5E8BC9',
  },
  {
    id: 'cripto',
    name: 'Criptomoedas',
    shortName: 'Cripto',
    category: 'crypto',
    rateBasis: 'custom',
    defaultRate: 20,
    customRate: 20,
    flatTaxRate: 0.15,
    taxExempt: false,
    fgcProtected: false,
    risk: 'high',
    liquidity: 'daily',
    minInvestment: 0,
    color: '#E0A23B',
  },
]

export const INVESTMENT_TYPE_MAP: Record<string, InvestmentType> =
  Object.fromEntries(INVESTMENT_TYPES.map((type) => [type.id, type]))

export function getInvestmentType(id: string): InvestmentType | undefined {
  return INVESTMENT_TYPE_MAP[id]
}
